[workspace]
authors = []
channels = ["conda-forge"]
name = "rdl-quantum-head"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
uv = "*"
python = "==3.10"

[pypi-options]
index-url = "https://pypi.org/simple"
find-links = [{ url = "https://data.pyg.org/whl/torch-2.7.0+cu126.html" }]

[pypi-dependencies]
pyg-lib = "*"
rdl-quantum-head = { path = ".", editable = true, extras = ["dev", "test"] }
